apiVersion: 1
datasources:
  - name: HealthData
    type: frser-sqlite-datasource
    uid: health-sqlite
    access: proxy
    jsonData:
      path: /var/lib/grafana/data/health.db
    isDefault: true
